# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=false
org.gradle.configuration-cache=false
# Mod properties
mod.id=zako
mod.version=0.1.0-SNAPSHOT
mod.group=dev.aika.zako
# "release", "beta" or "alpha"
mod.release_type=alpha
mod.game_version_supports=1.21,1.21.1
mod.enabled_platforms=fabric,neoforge
# Publishing
modrinth_id=
curseforge_id=
# Minecraft properties
minecraft_version=1.21.1
parchment_version=2024.11.17
fabric_loader=0.16.7
neoforge_version=21.1.145
# Dev dependencies
deps.fabric_api=0.107.0+1.21.1
deps.modmenu=11.0.1
# Dependencies
